#!/bin/sh
set -eu

usage() {
    cat <<'USAGE'
Usage: scripts/package-notice-bundle.sh <destination>

Destination may be:
  - a macOS .app bundle (the script writes into Contents/Resources/ThirdPartyNotices), or
  - any staging directory (the script writes into <destination>/ThirdPartyNotices).
USAGE
}

if [ "$#" -ne 1 ]; then
    usage >&2
    exit 64
fi

case "$1" in
    *.app)
        resources_root="$1/Contents/Resources"
        ;;
    *)
        resources_root="$1"
        ;;
esac

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
source_root="$repo_root/docs/notice-bundle"
bundle_root="$resources_root/ThirdPartyNotices"
ffmpeg_root="$bundle_root/FFmpeg"
external_root="$bundle_root/ExternalLibraries"

require_file() {
    if [ ! -f "$1" ]; then
        echo "error: required file missing: $1" >&2
        exit 1
    fi
}

for path in \
    "$source_root/README.md" \
    "$source_root/THIRD-PARTY-NOTICES.md" \
    "$source_root/SOURCE-OFFER.md" \
    "$repo_root/docs/ffmpeg-licensing.md" \
    "$repo_root/docs/ffmpeg-provenance.md" \
    "$source_root/licenses/ffmpeg-COPYING.LGPLv2.1.txt" \
    "$source_root/licenses/libmp3lame-COPYING.txt" \
    "$source_root/licenses/libmp3lame-LICENSE.txt" \
    "$source_root/licenses/libopus-COPYING.txt" \
    "$source_root/licenses/libvorbis-COPYING.txt" \
    "$source_root/licenses/libogg-COPYING.txt"
 do
    require_file "$path"
 done

rm -rf "$bundle_root"
mkdir -p "$ffmpeg_root" "$external_root"

cp "$source_root/README.md" "$bundle_root/README.md"
cp "$source_root/THIRD-PARTY-NOTICES.md" "$bundle_root/THIRD-PARTY-NOTICES.md"
cp "$source_root/SOURCE-OFFER.md" "$bundle_root/SOURCE-OFFER.md"
cp "$repo_root/docs/ffmpeg-licensing.md" "$ffmpeg_root/ffmpeg-licensing.md"
cp "$repo_root/docs/ffmpeg-provenance.md" "$ffmpeg_root/ffmpeg-provenance.md"
cp "$source_root/licenses/ffmpeg-COPYING.LGPLv2.1.txt" "$ffmpeg_root/COPYING.LGPLv2.1.txt"
cp "$source_root/licenses/libmp3lame-COPYING.txt" "$external_root/libmp3lame-COPYING.txt"
cp "$source_root/licenses/libmp3lame-LICENSE.txt" "$external_root/libmp3lame-LICENSE.txt"
cp "$source_root/licenses/libopus-COPYING.txt" "$external_root/libopus-COPYING.txt"
cp "$source_root/licenses/libvorbis-COPYING.txt" "$external_root/libvorbis-COPYING.txt"
cp "$source_root/licenses/libogg-COPYING.txt" "$external_root/libogg-COPYING.txt"

cat > "$bundle_root/NOTICE-MANIFEST.txt" <<MANIFEST
AudioConverter distribution notice bundle
Generated by: scripts/package-notice-bundle.sh
Generated at (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)

Included files:
- README.md
- SOURCE-OFFER.md
- THIRD-PARTY-NOTICES.md
- FFmpeg/ffmpeg-licensing.md
- FFmpeg/ffmpeg-provenance.md
- FFmpeg/COPYING.LGPLv2.1.txt
- ExternalLibraries/libmp3lame-COPYING.txt
- ExternalLibraries/libmp3lame-LICENSE.txt
- ExternalLibraries/libopus-COPYING.txt
- ExternalLibraries/libvorbis-COPYING.txt
- ExternalLibraries/libogg-COPYING.txt
MANIFEST

(
    cd "$bundle_root"
    find . -type f ! -name 'NOTICE-MANIFEST.sha256' | sort | while IFS= read -r file; do
        shasum -a 256 "$file"
    done > NOTICE-MANIFEST.sha256
)

echo "Packaged notice bundle at $bundle_root"
